src/Entity/Compte.php
<?php

namespace App\Entity;

use App\Repository\CompteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use Symfony\Component\Serializer\Annotation\Groups;

#[ApiResource(
        operations: [
            new Get(normalizationContext: ['groups' => 'compte:item']),
            new GetCollection(normalizationContext: ['groups' => 'compte:list'])
       ],

    paginationEnabled: false,
)]

#[ORM\Entity(repositoryClass: CompteRepository::class)]
class Compte implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['compte:list', 'compte:item'])]

    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Groups(['compte:list', 'compte:item'])]

    private ?string $username = null;

    #[ORM\Column]
    #[Groups(['compte:list', 'compte:item'])]

    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Groups(['compte:list', 'compte:item'])]

    private ?string $password = null;

    #[ORM\ManyToOne]
    #[Groups(['compte:list', 'compte:item'])]

    private ?Photo $photo_id = null;

    #[ORM\ManyToOne]
    #[Groups(['compte:list', 'compte:item'])]

    private ?Etablissement $etablissement_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['compte:list', 'compte:item'])]

    private ?string $biographie = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups(['compte:list', 'compte:item'])]

    private ?\DateTimeInterface $dernier_goldden_like = null;

    #[ORM\Column(length: 255)]
    #[Groups(['compte:list', 'compte:item'])]

    private ?string $email = null;

    #[ORM\Column(length: 30, nullable: true)]
    #[Groups(['compte:list', 'compte:item'])]

    private ?string $nom_affichage = null;

    #[ORM\Column]
    #[Groups(['compte:list', 'compte:item'])]

    private ?bool $suspendu = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPhotoId(): ?Photo
    {
        return $this->photo_id;
    }

    public function setPhotoId(?Photo $photo_id): static
    {
        $this->photo_id = $photo_id;

        return $this;
    }

    public function getEtablissementId(): ?Etablissement
    {
        return $this->etablissement_id;
    }

    public function setEtablissementId(?Etablissement $etablissement_id): static
    {
        $this->etablissement_id = $etablissement_id;

        return $this;
    }

    public function getBiographie(): ?string
    {
        return $this->biographie;
    }

    public function setBiographie(?string $biographie): static
    {
        $this->biographie = $biographie;

        return $this;
    }

    public function getDernierGolddenLike(): ?\DateTimeInterface
    {
        return $this->dernier_goldden_like;
    }

    public function setDernierGolddenLike(?\DateTimeInterface $dernier_goldden_like): static
    {
        $this->dernier_goldden_like = $dernier_goldden_like;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getNomAffichage(): ?string
    {
        return $this->nom_affichage;
    }

    public function setNomAffichage(?string $nom_affichage): static
    {
        $this->nom_affichage = $nom_affichage;

        return $this;
    }

    public function isSuspendu(): ?bool
    {
        return $this->suspendu;
    }

    public function setSuspendu(bool $suspendu): static
    {
        $this->suspendu = $suspendu;

        return $this;
    }
}

src/Entity/Like.php
<?php

namespace App\Entity;

use App\Repository\LikeRepository;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: LikeRepository::class)]
#[ApiResource(
    operations: [
        new Get(normalizationContext: ['groups' => 'like:item']),
        new GetCollection(normalizationContext: ['groups' => 'like:list'])
    ],
    paginationEnabled: false,
)]
#[ORM\Table(name: '`like`')]
class Like
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['like:list', 'like:item'])]

    private ?int $id = null;

    #[ORM\Column(nullable: false)]
    #[Groups(['like:list', 'like:item'])]

    private ?bool $golden = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['like:list', 'like:item'])]

    private ?Post $post_id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['like:list', 'like:item'])]

    private ?Compte $compte_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function isGolden(): ?bool
    {
        return $this->golden;
    }

    public function setGolden(bool $golden): static
    {
        $this->golden = $golden;

        return $this;
    }

    public function getPostId(): ?Post
    {
        return $this->post_id;
    }

    public function setPostId(?Post $post_id): static
    {
        $this->post_id = $post_id;

        return $this;
    }

    public function getCompteId(): ?Compte
    {
        return $this->compte_id;
    }

    public function setCompteId(?Compte $compte_id): static
    {
        $this->compte_id = $compte_id;

        return $this;
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: PostRepository::class)]
#[ApiResource(
    operations: [
        new Get(normalizationContext: ['groups' => 'post:item']),
        new GetCollection(normalizationContext: ['groups' => 'post:list'])
    ],
    paginationEnabled: false,
)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['post:list', 'post:item'])]
    private ?int $id = null;

    #[ORM\Column(length: 75, nullable: true)]
    #[Groups(['post:list', 'post:item'])]
    private ?string $titre = null;

    #[ORM\Column(length: 2200, nullable: true)]
    #[Groups(['post:list', 'post:item'])]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups(['post:list', 'post:item'])]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups(['post:list', 'post:item'])]
    private ?\DateTimeInterface $temps_retard = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['post:list', 'post:item'])]
    private ?Compte $compte_id = null;

    #[ORM\ManyToOne(targetEntity: Commentaire::class)]
    #[ORM\JoinColumn(nullable: true)]
    #[Groups(['post:item'])]
    private ?Commentaire $commentaireId = null;

    #[ORM\OneToMany(mappedBy: "post", targetEntity: Commentaire::class)]
    #[Groups(['post:item'])]
    private Collection $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;
        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): static
    {
        $this->titre = $titre;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;
        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;
        return $this;
    }

    public function getTempsRetard(): ?\DateTimeInterface
    {
        return $this->temps_retard;
    }

    public function setTempsRetard(\DateTimeInterface $temps_retard): static
    {
        $this->temps_retard = $temps_retard;
        return $this;
    }

    public function getCompteId(): ?Compte
    {
        return $this->compte_id;
    }

    public function setCompteId(?Compte $compte_id): static
    {
        $this->compte_id = $compte_id;
        return $this;
    }

    public function getCommentaireId(): ?Commentaire
    {
        return $this->commentaireId;
    }

    public function setCommentaireId(?Commentaire $commentaireId): static
    {
        $this->commentaireId = $commentaireId;
        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setPost($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getPost() === $this) {
                $commentaire->setPost(null);
            }
        }

        return $this;
    }
}

templates/home/add_commentaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un commentaire{% endblock %}

{% block body %}
    <div class="container">
        <h1>Ajouter un commentaire</h1>
        <form action="{{ path('app_add_comment', {'id': post.id}) }}" method="post">
            {{ form_start(commentaireForm) }}
            {{ form_row(commentaireForm.texte) }}
            <button type="submit" class="btn btn-primary">Ajouter le commentaire</button>
            {{ form_end(commentaireForm) }}
        </form>
    </div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TardyGrade{% endblock %}

{% block body %}
    <div class="container">
        <h1>Créer un retard</h1>
        <!-- Formulaire de création de retard -->
        <form action="{{ path('app_create_post') }}" method="post">
            <!-- Champs pour le titre, la description et la durée du retard -->
            <div class="form-group">
                <label for="titre">Titre :</label>
                <input type="text" id="titre" name="titre" class="form-control">
            </div>
            <div class="form-group">
                <label for="description">Description :</label>
                <textarea id="description" name="description" class="form-control"></textarea>

                <label for="duree_retard">Durée du retard (en minutes) :</label>
                <input type="number" id="duree_retard" name="duree_retard" class="form-control">
            </div>
            <div class="form-group">
                <label for="hashtags">Choisir un # :</label>
                <select id="hashtags" name="hashtags[]" class="form-control">
                    <option value="">Sélectionner un #</option>
                    <option value="#Important">#Important</option>
                    <option value="#Urgent">#Urgent</option>
                    <option value="#Meeting">#Meeting</option>
                    <option value="#Client">#Client</option>
                    <option value="#Project">#Project</option>
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Créer</button>
        </form>

        <br>
        <br>
        <h1>Publications</h1>
        <!-- Liste des publications -->
        {% if publications %}
            <ul class="list-group">
                {% for publication in publications %}
                    <li class="list-group-item">
                        <p>Créé par : {{ publication.compteId.username }}</p>
                        <div>

                        <h4>{{ publication.titre }}</h4>
                        <p>{{ publication.description }}</p>
                        <p>Durée du retard : {{ publication.tempsRetard|date('H:i') }}</p>

                        <!-- Bouton Like -->
                        <div class="btn-group" role="group">
                            <form action="{{ path('app_like_post', {'id': publication.id}) }}" method="post">
                                <button type="submit" class="btn btn-success like-btn" data-post-id="{{ publication.id }}">
                                    <i class="fas fa-thumbs-up"></i> Like <span class="like-count">{{ likesCount[publication.id]|default(0) }}</span>
                                </button>
                            </form>

                            <!-- Bouton Super Like -->
                            <form action="{{ path('app_home', {'id': publication.id}) }}" method="post">
                                <button type="submit" class="btn btn-warning super-like-btn" data-post-id="{{ publication.id }}">
                                    <i class="fas fa-star"></i> Super Like <span class="super-like-count">0</span>
                                </button>
                            </form>
                        </div>

                            {% for item in publicationsWithComments %}
                                {% set publication = item.publication %}
                                <div>


                                    <!-- Affichage des commentaires -->
                                    <div class="mt-3">
                                        <h5>Commentaires :</h5>
                                        {% if item.commentaires is not empty %}
                                            <ul class="list-unstyled">
                                                {% for commentaire in item.commentaires %}
                                                    <li>
                                                        <p><strong>{{ commentaire.compteId.username }}</strong> - {{ commentaire.date|date('d/m/Y H:i') }}</p>
                                                        <p>{{ commentaire.texte }}</p>
                                                    </li>
                                                {% endfor %}
                                            </ul>
                                        {% else %}
                                            <p>Aucun commentaire pour le moment.</p>
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}


                        </div>
                            <form action="{{ path('app_add_comment', {'id': publication.id}) }}" method="post">
                                <label for="commentaire">Commentaire :</label>
                                <textarea id="commentaire" name="commentaire" class="form-control"></textarea>
                                <button type="submit" class="btn btn-primary">Ajouter un commentaire</button>
                            </form>
                            <form action="{{ path('app_modify_post', {'id': publication.id}) }}" method="post">
                                <button type="submit" class="btn btn-primary">Modifier</button>



                        <!-- Formulaire pour signaler la publication -->
                        <form action="{{ path('app_signalement', {'id': publication.id}) }}" method="post">
                            <label for="motif">Motif du signalement :</label>
                            <textarea id="motif" name="motif" class="form-control"></textarea>
                            <button type="submit" class="btn btn-warning super-like-btn" data-post-id="{{ publication.id }}">
                                <i class="fas fa-star"></i> Signaler <span class="signalement-count">{{ signalementsCount[publication.id]|default(0) }}</span>
                            </button>
                        </form>

                        <!-- Bouton pour supprimer la publication (si l'utilisateur est l'auteur) -->
                        {% if publication.compteId == compte %}
                            <a href="{{ path('app_delete_post', {'id': publication.id}) }}" class="btn btn-danger">Supprimer</a>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="lead">Aucune publication disponible.</p>
        {% endif %}
    </div>
    <!-- Inclure la bibliothèque Font Awesome -->
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const likeButtons = document.querySelectorAll('.like-btn');
            const superLikeButtons = document.querySelectorAll('.super-like-btn');
            const commentButtons = document.querySelectorAll('.comment-btn');

            likeButtons.forEach(function(button) {
                button.addEventListener('click', function(event) {
                    const postId = this.getAttribute('data-post-id');
                    // Augmenter le compteur de likes et mettre à jour le texte du bouton
                    const likeCountElement = this.querySelector('.like-count');
                    likeCountElement.textContent = parseInt(likeCountElement.textContent) + 1;
                });
            });

            superLikeButtons.forEach(function(button) {
                button.addEventListener('click', function(event) {
                    const postId = this.getAttribute('data-post-id');
                    // Augmenter le compteur de super likes et mettre à jour le texte du bouton
                    const superLikeCountElement = this.querySelector('.super-like-count');
                    superLikeCountElement.textContent = parseInt(superLikeCountElement.textContent) + 1;
                });
            });

            commentButtons.forEach(function(button) {
                button.addEventListener('click', function(event) {
                    const postId = this.getAttribute('data-post-id');
                    // Rediriger l'utilisateur vers la page de commentaire ou afficher un formulaire de commentaire
                    console.log('Commented on post with ID:', postId);
                });
            });
        });
    </script>
{% endblock %}

templates/home/modif_commentaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la publication{% endblock %}

{% block body %}
    <div class="container">
        <h1>Modifier la publication</h1>
        <form action="{{ path('app_modify_post', {'id': post.id}) }}" method="post">
            {{ form_start(form) }}
            <div class="form-group">
                {{ form_label(form.titre) }}
                {{ form_widget(form.titre, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.titre) }}
            </div>
            <div class="form-group">
                {{ form_label(form.description) }}
                {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.description) }}
            </div>
            <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>
            {{ form_end(form) }}
        </form>
    </div>
{% endblock %}

templates/home/modif_post.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la publication{% endblock %}

{% block body %}
    <div class="container">
        <h1>Modifier la publication</h1>
        <form action="{{ path('app_modify_post', {'id': post.id}) }}" method="post">
            {{ form_start(form) }}
            <div class="form-group">
                {{ form_label(form.titre) }}
                {{ form_widget(form.titre, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.titre) }}
            </div>
            <div class="form-group">
                {{ form_label(form.description) }}
                {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.description) }}
            </div>
            <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>
            {{ form_end(form) }}
        </form>

    </div>
{% endblock %}

templates/home/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}TardyGrade{% endblock %}

{% block body %}

    <div class='container'>
        <h2 class='text-center'>Résultats de recherche</h2>

        <div class="w-50 d-flex justify-content-center align-items-center flex-column m-auto">
            {% if comptes is not empty %}
                <h2 class="w-100 mt-2">Comptes :</h2>
            {% endif %}
            {% for compte in comptes %}
                <div class='card w-100 mt-2'>
                    <div class='card-body'>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{{ path('app_compte_show', {'id': compte.getId()}) }}" class="text-decoration-none text-dark">
                                    <h5 class='card-title
                                        {% if compte.getUsername() == 'Retarrosoir' %}
                                            text-danger
                                        {% endif %}
                                        '>@{{ compte.getUsername() }}</h5>
                                </div>
                            </a>

                            <div>

                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="w-50 d-flex justify-content-center align-items-center flex-column m-auto">
            {% if etablissements is not empty %}
                <h2 class="w-100 mt-2">Etablissements : </h2>
            {% endif %}
            {% for etablissement in etablissements %}
                <div class='card w-100 mt-2'>
                    <div class='card-body'>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{{ path('app_etablissement_show', {'id': etablissement.getId()}) }}" class="text-decoration-none text-dark">
                                <div class="d-flex gap-3 align-items-center">
                                    {% if etablissement.photoId %}
                                        <img src="data:image/{{ etablissement.photoId.getFormatId().getNom() }};base64,{{ etablissement.getPhotoId().getDonneesPhoto() }}" alt="Photo de profil" width="50px" height="50px" class="rounded-circle border border-dark">
                                    {% else %}
                                        <div class="rounded-circle bg-secondary" style="width: 50px; height: 50px;"></div>
                                    {% endif %}
                                    <h5 class='card-title
                                    {% if etablissement.getNom() == 'Retarrosoir' %}
                                        text-danger
                                    {% endif %}
                                    '>@{{ etablissement.getNom() }}</h5>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>

        <div class="w-50 d-flex justify-content-center align-items-center flex-column m-auto">
            {% if publications is not empty %}
                <h2 class="w-100 mt-2">Publications : </h2>
            {% endif %}
            {% for publication in publications %}
                <div class='card w-100 mt-2'>
                    <div class='card-body'>
                        <h5 class='card-title'>{{ publication.getTitre() }}</h5>
                        <p class='card-text'>{{ publication.getDescription() }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}