src/Entity/Compte.php
<?php

namespace App\Entity;

use App\Repository\CompteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use Symfony\Component\Serializer\Annotation\Groups;

#[ApiResource(
        operations: [
            new Get(normalizationContext: ['groups' => 'compte:item']),
            new GetCollection(normalizationContext: ['groups' => 'compte:list'])
       ],

    paginationEnabled: false,
)]

#[ORM\Entity(repositoryClass: CompteRepository::class)]
class Compte implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['compte:list', 'compte:item'])]

    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Groups(['compte:list', 'compte:item'])]

    private ?string $username = null;

    #[ORM\Column]
    #[Groups(['compte:list', 'compte:item'])]

    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Groups(['compte:list', 'compte:item'])]

    private ?string $password = null;

    #[ORM\ManyToOne]
    #[Groups(['compte:list', 'compte:item'])]

    private ?Photo $photo_id = null;

    #[ORM\ManyToOne]
    #[Groups(['compte:list', 'compte:item'])]

    private ?Etablissement $etablissement_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['compte:list', 'compte:item'])]

    private ?string $biographie = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups(['compte:list', 'compte:item'])]

    private ?\DateTimeInterface $dernier_goldden_like = null;

    #[ORM\Column(length: 255)]
    #[Groups(['compte:list', 'compte:item'])]

    private ?string $email = null;

    #[ORM\Column(length: 30, nullable: true)]
    #[Groups(['compte:list', 'compte:item'])]

    private ?string $nom_affichage = null;

    #[ORM\Column]
    #[Groups(['compte:list', 'compte:item'])]

    private ?bool $suspendu = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPhotoId(): ?Photo
    {
        return $this->photo_id;
    }

    public function setPhotoId(?Photo $photo_id): static
    {
        $this->photo_id = $photo_id;

        return $this;
    }

    public function getEtablissementId(): ?Etablissement
    {
        return $this->etablissement_id;
    }

    public function setEtablissementId(?Etablissement $etablissement_id): static
    {
        $this->etablissement_id = $etablissement_id;

        return $this;
    }

    public function getBiographie(): ?string
    {
        return $this->biographie;
    }

    public function setBiographie(?string $biographie): static
    {
        $this->biographie = $biographie;

        return $this;
    }

    public function getDernierGolddenLike(): ?\DateTimeInterface
    {
        return $this->dernier_goldden_like;
    }

    public function setDernierGolddenLike(?\DateTimeInterface $dernier_goldden_like): static
    {
        $this->dernier_goldden_like = $dernier_goldden_like;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getNomAffichage(): ?string
    {
        return $this->nom_affichage;
    }

    public function setNomAffichage(?string $nom_affichage): static
    {
        $this->nom_affichage = $nom_affichage;

        return $this;
    }

    public function isSuspendu(): ?bool
    {
        return $this->suspendu;
    }

    public function setSuspendu(bool $suspendu): static
    {
        $this->suspendu = $suspendu;

        return $this;
    }
}

src/Entity/Etablissement.php
<?php

namespace App\Entity;

use App\Repository\EtablissementRepository;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: EtablissementRepository::class)]
#[ApiResource(
    operations: [
        new Get(normalizationContext: ['groups' => 'etablissement:item']),
        new GetCollection(normalizationContext: ['groups' => 'etablissement:list'])
    ],
    paginationEnabled: false,
)]
class Etablissement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['etablissement:list', 'etablissement:item'])]

    private ?int $id = null;

    #[ORM\Column(length: 25)]
    #[Groups(['etablissement:list', 'etablissement:item'])]

    private ?string $nom = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['etablissement:list', 'etablissement:item'])]

    private ?int $code_postal = null;

    #[ORM\Column(length: 25, nullable: true)]
    #[Groups(['etablissement:list', 'etablissement:item'])]

    private ?string $pays = null;

    #[ORM\ManyToOne]
    #[Groups(['etablissement:list', 'etablissement:item'])]

    private ?Photo $photo_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(?int $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(?string $pays): static
    {
        $this->pays = $pays;

        return $this;
    }

    public function getPhotoId(): ?Photo
    {
        return $this->photo_id;
    }

    public function setPhotoId(?Photo $photo_id): static
    {
        $this->photo_id = $photo_id;

        return $this;
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\Compte;
use App\Entity\Abonnement;
use App\Entity\Signalement;
use App\Entity\Photo;
use App\Entity\Format;
use App\Form\CompteType;
use App\Form\EtablissementType;
use App\Entity\Post;
use App\Entity\Etablissement;

use App\Repository\CompteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\File;

#[Route('/compte')]
class CompteController extends AbstractController
{
    public function __construct(AuthorizationCheckerInterface $authorizationChecker)

    {
        $this->authorizationChecker = $authorizationChecker;
    }


    #[Route('/', name: 'app_compte_index', methods: ['GET'])]
    public function index(CompteRepository $compteRepository): Response
    {
        return $this->render('compte/index.html.twig', [
            'comptes' => $compteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_compte_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $hasher): Response
    {
        $compte = new Compte();
        $form = $this->createForm(CompteType::class, $compte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Associer l'établissement sélectionné au compte
            $compte->setEtablissementId($form->get('etablissement_id')->getData());

            $compte->setUsername($compte->getUsername());
            $compte->setPassword($hasher->hashPassword($compte, $compte->getPassword()));
            $compte->setRoles(['ROLE_USER']);
            $compte->setSuspendu(false);

            $entityManager->persist($compte);
            $entityManager->flush();

            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('compte/new.html.twig', [
            'compte' => $compte,
            'form' => $form,
        ]);
    }


    #[Route('/{id}', name: 'app_compte_show', methods: ['GET'])]
    public function show(Compte $compte, EntityManagerInterface $em): Response
    {
        // Vérifier si le compte connecté est abonné au compte affiché uniquement si le compte n'est pas le sien
        $user = $this->getUser();
        $abonne = false;
        $donneesPhoto = null;
        $format = null;

        // Je dois récupérer la photo de profil
        $photo = $compte->getPhotoId();

        if ($photo) {
            $format = $photo->getFormatId();
            $donneesPhoto = stream_get_contents($photo->getDonneesPhoto());
        }

        if ($user !== null && $compte !== $user) {
            $abonnement = $em->getRepository(Abonnement::class)->findOneBy([
                'suiveur_id' => $user,
                'suivi_personne_id' => $compte
            ]);

            if ($abonnement !== null) {
                // Si un abonnement est trouvé, alors le compte connecté est abonné au compte affiché
                $abonne = true;
            }
        }

        return $this->render('compte/show.html.twig', [
            'compte' => $compte,
            'abonne' => $abonne,
            'donneesPhoto' => $donneesPhoto != null ? base64_encode($donneesPhoto) : $donneesPhoto,
            'format' => $format != null ? $format->getNom() : $format
        ]);
    }

    #[Route('/{id}/edit', name: 'app_compte_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Compte $compte, EntityManagerInterface $entityManager, UserPasswordHasherInterface $hasher): Response
    {
        $form = $this->createForm(CompteType::class, $compte);
        $form->handleRequest($request);

        // On doit récupérer le nouveau mot de passe

        if ($form->isSubmitted() && $form->isValid()) {

            // Il faut modifier la photo de profil si elle a été modifiée
            if ($form->get('data')->getData() != null) {
                $photo = $compte->getPhotoId();
                $photo->setDonneesPhoto(file_get_contents($form->get('data')->getData()));
                $entityManager->persist($photo);

                // On récupère le type de la photo
                $type = $form->get('data')->getData()->getMimeType();

                // On ajoute un nouveau format pour la photo si il n'existe pas sinon on récupère le format existant et on attribue à la photo l'id du format
                $format = $entityManager->getRepository(Format::class)->findOneBy(['nom' => $type]);

                if (!$format) {
                    $format = new Format();
                    $format->setNom($type);
                    $entityManager->persist($format);
                }

                $photo->setFormatId($format);

                $compte->setPhotoId($photo);
            }

            // Il faut modifier le mot de passe en le hashant
            $compte->setPassword($hasher->hashPassword($compte, $compte->getPassword()));

            $entityManager->flush();

            return $this->redirectToRoute('app_compte_show', ['id' => $compte->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('compte/edit.html.twig', [
            'compte' => $compte,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_compte_delete', methods: ['POST'])]
    public function delete(Request $request, Compte $compte, EntityManagerInterface $entityManager): Response
    {
        // Récupérer l'utilisateur connecté
        $user = $this->getUser();

        // Vérifier si l'utilisateur connecté est le propriétaire du compte à supprimer
        if ($user === $compte) {
            // Vérifier si le jeton CSRF est valide
            if ($this->isCsrfTokenValid('delete'.$compte->getId(), $request->request->get('_token'))) {
                $entityManager->remove($compte);
                $entityManager->flush();
            }
        } else {
            // Rediriger avec un message d'erreur ou renvoyer une réponse d'erreur
            // Selon vos besoins
            return $this->redirectToRoute('app_compte_index', [], Response::HTTP_FORBIDDEN);
        }

        return $this->redirectToRoute('app_compte_index', [], Response::HTTP_SEE_OTHER);
    }


    // Je veux créer une route pour s'abonner à un compte
    #[Route('/subscribe/{id}', name: 'app_subscribe')]
    public function subscribe($id, EntityManagerInterface $em, UserInterface $user): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');

        $compte = $user;

        $compteToSubscribe = $em->getRepository(Compte::class)->find($id);

        if (!$compteToSubscribe) {
            throw $this->createNotFoundException('Compte non trouvé');
        }

        $abonnement = new Abonnement();
        $abonnement->setSuiveurId($compte);
        $abonnement->setSuiviPersonneId($compteToSubscribe);

        $em->persist($abonnement);
        $em->flush();

        return $this->redirectToRoute('app_compte_show', ['id' => $id]);
    }

    // Je veux créer une route pour se désabonner d'un compte
    #[Route('/unsubscribe/{id}', name: 'app_unsubscribe')]
    public function unsubscribe($id, EntityManagerInterface $em, UserInterface $user): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');

        $compte = $user;

        $compteToUnsubscribe = $em->getRepository(Compte::class)->find($id);

        if (!$compteToUnsubscribe) {
            throw $this->createNotFoundException('Compte non trouvé');
        }

        $abonnement = $em->getRepository(Abonnement::class)->findOneBy([
            'suiveur_id' => $compte,
            'suivi_personne_id' => $compteToUnsubscribe
        ]);

        if (!$abonnement) {
            throw $this->createNotFoundException('Abonnement non trouvé');
        }

        $em->remove($abonnement);
        $em->flush();

        return $this->redirectToRoute('app_compte_show', ['id' => $id]);
    }

    #[Route('/abonnements/{id}', name: 'app_compte_abonnements', methods: ['GET'])]
    public function abonnements(int $id, EntityManagerInterface $em): Response
    {
        // Récupérer le compte à partir de l'ID
        $compte = $em->getRepository(Compte::class)->find($id);

        // Vérifier si le compte a été trouvé
        if (!$compte) {
            throw $this->createNotFoundException('Compte non trouvé');
        }

        // Récupérer les abonnements du compte
        $abonnements = $em->getRepository(Abonnement::class)->findBy(['suiveur_id' => $compte]);

        return $this->render('compte/abonnements.html.twig', [
            'abonnements' => $abonnements,
        ]);
    }

    // Route pour signaler un compte

    #[Route('/signaler/{id}', name: 'app_compte_signaler', methods: ['GET'])]
    public function signaler($id, EntityManagerInterface $em, Request $request): Response
    {
        $compte = $em->getRepository(Compte::class)->find($id);

        // Vérifier si le compte existe
        if (!$compte) {
            throw $this->createNotFoundException('Compte non trouvé');
        }

        // Créer un nouveau signalement
        $signalement = new Signalement();
        $signalement->setSignaleurId($this->getUser());
        $signalement->setSignaleId($compte);

        // Récupérer le motif du signalement depuis la requête
        $motif = $request->query->get('motif');

        // Vérifier si le motif est défini
        if ($motif !== null) {
            $signalement->setMotif($motif);

            // Enregistrer le signalement dans la base de données
            $em->persist($signalement);

templates/compte/_delete_form.html.twig
<form method="post" action="{{ path('app_compte_delete', {'id': compte.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer ce compte ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ compte.id) }}">
    <button class="btn btn-danger">Supprimer le compte</button>
</form>

templates/compte/_form.html.twig
{{ form_start(form) }}

{{ form_row(form.data) }}

<div class="d-flex justify-content-between align-items-center gap-3 w-100">
    <div class="w-75">
        {{ form_row(form.etablissement_id) }}
    </div>
    <a href="{{ path('app_etablissement_new') }}" class="btn btn-primary">Nouveau</a>
</div>

{{ form_row(form.username) }}
{{ form_row(form.nom_affichage) }}
{{ form_row(form.email) }}
{{ form_row(form.password) }}
{{ form_row(form.biographie) }}

<button class="btn btn-primary">{{ button_label|default("S'inscrire") }}</button>

<div>
    {% if app.request.attributes.get('_route') == 'app_compte_new' %}
        <span class="mt-2">Déjà un compte ? <a href="{{ path('app_login') }}">Se connecter</a></span>
    {% endif %}
</div>

{{ form_end(form) }}

templates/compte/abonnements.html.twig
{% extends 'base.html.twig' %}

{% block title %}TardyGrade{% endblock %}

{% block body %}
    <h2>Abonnements</h2>

    {% for abonnement in abonnements %}
        <div class="card">
            {% if abonnement.getSuiviPersonneId() is not null %}
                <div class="card-body">
                    <h5 class="card-title">{{ abonnement.getSuiviPersonneId().getUsername() }}</h5>
                    <a href="{{ path('app_compte_show', {'id': abonnement.getSuiviPersonneId().getId()}) }}" class="btn btn-primary">Voir</a>
                </div>
            {% elseif abonnement.getSuiviEtablissementId is not null %}
                <div class="card-body">
                    <h5 class="card-title">{{ abonnement.getSuiviEtablissementId().getNom() }}</h5>
                    <a href="{{ path('app_etablissement_show', {'id': abonnement.getSuiviEtablissementId().getId()}) }}" class="btn btn-primary">Voir</a>
                </div>
            {% endif %}

        </div>
    {% endfor %}

{% endblock %}

templates/compte/associate.html.twig
{# templates/etablissement/associate.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Associate{% endblock %}

{% block body %}
    <h1>Associate to an Etablissement</h1>

    {{ form_start(form) }}
    {{ form_row(form.etablissement) }}
    <button type="submit">Associate</button>
    {{ form_end(form) }}
{% endblock %}

templates/compte/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Compte{% endblock %}

{% block body %}

    <div class="container">

        <h1>Modifier le Compte</h1>
    
        {{ include('compte/_form.html.twig', {'button_label': 'Modifier'}) }}

        <div class="d-flex gap-6 mt-3">
        
            <a class="btn btn-primary" href="{{ path('app_compte_show', {id: compte.id}) }}">Retour</a>

            {{ include('compte/_delete_form.html.twig') }}

        </div>

    </div>

{% endblock %}

templates/compte/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Compte index{% endblock %}

{% block body %}
    <h1>Compte index</h1>

    <table class="table table bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_photo</th>
                <th>Id_etablissement</th>
                <th>Pseudo</th>
                <th>Nom_affichage</th>
                <th>Email</th>
                <th>Mdp</th>
                <th>Biographie</th>
                <th>Dernier_golden_like</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for compte in comptes %}
            <tr>
                <td>{{ compte.id }}</td>
                <td>{{ compte.etablissementId.nom }}</td>
                <td>{{ compte.username }}</td>
                <td>{{ compte.nomAffichage }}</td>
                <td>{{ compte.email }}</td>
                <td>{{ compte.password }}</td>
                <td>{{ compte.biographie }}</td>
                <td>{{ compte.dernierGolddenLike ? compte.dernierGolddenLike|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_compte_show', {'id': compte.id}) }}">show</a>
                    <a href="{{ path('app_compte_edit', {'id': compte.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_compte_new') }}">Create new</a>
{% endblock %}

templates/compte/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un Compte{% endblock %}

{% block body %}

    <div class="container">
        <div class="card w-50 p-5 mx-auto my-5">
            <h1>Inscrivez-vous</h1>
            {{ include('compte/_form.html.twig') }}
        </div>
    </div>

{% endblock %}

templates/compte/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Compte{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        /* Styles spécifiques au profil */
        .profile-container {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .profile-image {
            width: 200px;
            height: 200px;
            border-radius: 50%;
            overflow: hidden;
            border: 2px solid #007bff;
            margin-right: 20px;
        }
        .profile-image img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
        .profile-info {
            flex: 1;
        }
        .profile-actions {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: 20px;
        }
        .profile-actions a {
            text-decoration: none;
            color: #fff;
        }
        .profile-actions .btn {
            margin-right: 10px;
        }
        .publication-list {
            margin-top: 40px;
            list-style: none;
            padding: 0;
        }
        .publication-item {
            margin-bottom: 20px;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 8px;
        }
        /* Fin des styles spécifiques au profil */
    </style>
{% endblock %}

{% block body %}
    <div class="container profile-container">
        <div class="d-flex align-items-center">
            <div class="profile-image">
                {% if donneesPhoto %}
                    <img src="data:image/{{ format }};base64,{{ donneesPhoto }}" alt="Photo de profil">
                {% else %}
                    <div class="bg-secondary"></div>
                {% endif %}
            </div>
            <div class="profile-info">
                {% if compte is not null %}
                    <h2>{{ compte.nomAffichage }}</h2>
                    <p class="text-muted">@{{ compte.username }}</p>
                    <p>{{ compte.biographie }}</p>
                    <div class="card">
                        <div class="card-body">
                            {% if compte.etablissementId is not null %}
                                <h6 class="card-title">{{ compte.etablissementId.nom }}</h6>
                                <p class="card-text text-muted">Localisation: {{ compte.etablissementId.pays }}, {{ compte.etablissementId.codePostal }}</p>
                            {% else %}
                                <p class="card-text text-muted">Pas d'établissement associé</p>
                                {# Formulaire pour associer un établissement #}
                            {% endif %}
                        </div>
                    </div>
                    <div class="profile-actions">

                        {% if app.user is not null and app.user.id != compte.id %}
                            {% if abonne %}
                                <a href="{{ path('app_unsubscribe', {'id': compte.id}) }}" class="btn btn-danger">Se désabonner</a>
                            {% else %}
                                <a href="{{ path('app_subscribe', {'id': compte.id}) }}" class="btn btn-primary">S'abonner</a>
                            {% endif %}
                        {% endif %}
                        <a href="{{ path('app_compte_abonnements', {'id': compte.id}) }}" class="btn btn-primary">Abonnements</a>
                        <a href="{{ path('app_etablissement_index') }}" class="btn btn-primary">Associer à un établissement</a>
                        {% if app.user is not null and app.user.id == compte.id %}
                            <a href="{{ path('app_compte_edit', {'id': compte.id}) }}" class="btn btn-primary">Modifier le profil</a>
                        {% endif %}
                        {% if app.user is not null and app.user.id != compte.id %}
                            <a href="{{ path('app_compte_signaler', {'id': compte.id}) }}" class="btn btn-danger">Signaler</a>
                        {% endif %}
                    </div>
                {% else %}
                    <p>Compte non trouvé.</p>
                {% endif %}
            </div>
        </div>

        <hr>

        <h3 class="text-center">Mes Publications</h3>
        {% if publications %}
            <ul class="publication-list">
                {% for publication in publications %}
                    <li class="publication-item">
                        <h4>{{ publication.titre }}</h4>
                        <p>{{ publication.description }}</p>
                        <!-- Ajoutez les autres éléments ici comme vous l'avez fait dans votre exemple -->
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-center text-muted">Aucune publication pour le moment.</p>
        {% endif %}
    </div>
{% endblock %}